"""One-shot split freeze (master-plan Stage 6; data_collection_plan.md "Splits And Leakage").

Pins a calibrated, leakage-audited train/eval/diagnostic/qualitative partition of the CURRENT
accepted corpus so the tokenizer (and later warmup/SFT) train only on train identities and
never see the reserved eval/diagnostic/qualitative identities — permanently, reproducibly,
and restorably.

What it does (no data re-acquisition, deterministic):
  1. Loads accepted candidates (representability_tier in {gold, diagnostic_only}) from the
     provenance registry + their canonical residual tensors.
  2. Fits + PINS the PCA-64 LUT-behavior basis on the accepted pool (records pca_basis_sha256
     + pca_fit_set_version, which were TODO in the template config), and uses that ONE basis
     for BOTH split-unit assignment and leakage verification (self-consistent: near-duplicates
     are unioned into the same split unit, so the written report is clean by construction).
  3. Bumps leakage_policy_version off "v0" and verifies the split is leakage-clean on the
     ACTIVE axes: exact-hash (normalized_lut_hash) + LUT-behavior PCA-64 near-neighbor cosine.
     These are the axes that matter for the tokenizer (conditioned only on residual LUTs).
     The image/prompt semantic-near axes stay skipped: CLIP/MiniLM embeddings are not wired in
     leakage.py and prompt text is pending the teacher; they gate the downstream image+prompt
     SFT and are frozen separately when those inputs exist.
  4. Writes data/splits/{split_manifest.json, leakage_report.json} and BACKS THEM UP to
     data/splits/frozen/<split_id>/ (data/splits/ is gitignored, so `git add -f` that dir to
     make the freeze restorable) with a frozen_split.json marker.

Refuses to write if any active-axis cross-split leakage remains. `--dry-run` verifies without
writing. Run: `python -m data_pipeline.freeze_split` (or `slm_freeze_split`).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import yaml

from .leakage import LeakageChecker, LeakageItem, fit_lut_pca, leakage_report, load_thresholds
from .splits import DEFAULT_RATIOS, SplitCandidate, _bucket, assign_split_units

ACCEPTED_TIERS = ("gold", "diagnostic_only")


def _residual_key(row: dict):
    # pipeline residual filename precedence (matches tokenizer.data + run_pipeline)
    return (row.get("residual_key") or row.get("_residual_key") or row.get("lut_id")
            or row.get("source_pair_id") or row.get("file_hash"))


def load_accepted_candidates(root: str) -> tuple[list[SplitCandidate], dict]:
    """Build SplitCandidates for every accepted row (all splits), mirroring run_pipeline."""
    root = Path(root)
    prov = root / "data" / "raw_registry" / "provenance.jsonl"
    residual_dir = root / "luts" / "canonical_residual"
    rows = [json.loads(l) for l in prov.read_text(encoding="utf-8").splitlines() if l.strip()]

    cands: list[SplitCandidate] = []
    cov = {"accepted": 0, "with_residual": 0, "missing_residual": 0}
    for r in rows:
        if r.get("representability_tier") not in ACCEPTED_TIERS:
            continue
        cov["accepted"] += 1
        key = _residual_key(r)
        rp = residual_dir / f"{key}.npy"
        residual = None
        if key is not None and rp.exists():
            residual = np.load(rp).reshape(-1)
            cov["with_residual"] += 1
        else:
            cov["missing_residual"] += 1
        cands.append(SplitCandidate(
            id=r.get("file_hash") or str(key),
            base_key=(r.get("group_id") or r.get("source_photo_id")
                      or r.get("normalized_lut_hash") or str(key)),
            procedural=bool(r.get("procedural_filler")),
            lut_hash=r.get("canonical_residual_lut_hash"),
            residual_vec=residual,
        ))
    return cands, cov


def _corpus_id(cands: list[SplitCandidate]) -> str:
    h = hashlib.sha256()
    for lh in sorted(c.lut_hash or c.id for c in cands):
        h.update(lh.encode("utf-8"))
    return "corpus_" + h.hexdigest()[:16]


def write_frozen_thresholds(root: str, policy_version: str, pca_basis_sha256: str,
                            corpus_id: str) -> str:
    """Copy the template thresholds with the policy bumped + PCA basis pinned. Template untouched."""
    t = load_thresholds(Path(root) / "configs" / "leakage_thresholds.yaml")
    t["leakage_policy_version"] = policy_version
    t.setdefault("lut_behavior", {})
    t["lut_behavior"]["pca_basis_sha256"] = pca_basis_sha256
    t["lut_behavior"]["pca_fit_set_version"] = corpus_id
    out = Path(root) / "configs" / "leakage_thresholds.frozen.yaml"
    out.write_text(
        "# Auto-generated by data_pipeline.freeze_split — pinned/frozen leakage policy.\n"
        "# Derived from configs/leakage_thresholds.yaml with the policy version bumped and the\n"
        "# LUT-behavior PCA basis pinned. Do not hand-edit.\n"
        + yaml.safe_dump(t, sort_keys=False),
        encoding="utf-8",
    )
    return str(out)


def _split_id(assignments: dict) -> str:
    return "split_" + hashlib.sha256(
        ("|".join(f"{k}:{v['split']}" for k, v in sorted(assignments.items()))).encode()
    ).hexdigest()[:16]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Freeze the data split (Stage 6). Runs only when invoked.")
    ap.add_argument("--root", default=".")
    ap.add_argument("--policy-version", default="frozen_v1",
                    help="leakage_policy_version to pin (must differ from 'v0')")
    ap.add_argument("--seed", type=int, default=1234, help="split-assignment seed (recorded)")
    ap.add_argument("--dry-run", action="store_true", help="build + verify + report; write nothing")
    args = ap.parse_args(argv)
    root = Path(args.root)

    if args.policy_version == "v0":
        print("[abort] --policy-version must be bumped off 'v0' to freeze (the template default).")
        return 2

    cands, cov = load_accepted_candidates(args.root)
    if not cands:
        print("[abort] no accepted candidates in the registry — nothing to freeze.")
        return 2
    print(f"[freeze] accepted candidates: {cov['accepted']} "
          f"(with residual {cov['with_residual']}, missing {cov['missing_residual']})")

    res_vecs = [c.residual_vec for c in cands if c.residual_vec is not None]
    if len(res_vecs) < 2:
        print("[abort] need >=2 residual tensors to fit the LUT-behavior PCA basis.")
        return 2

    # Pin ONE PCA-64 basis (fit on the accepted pool) and use it for BOTH assignment and
    # verification via a single shared checker -> the written report is self-consistent.
    pca = fit_lut_pca(res_vecs, dim=64)
    corpus_id = _corpus_id(cands)
    frozen_cfg = write_frozen_thresholds(args.root, args.policy_version, pca.basis_sha256, corpus_id)
    checker = LeakageChecker(load_thresholds(frozen_cfg), pca=pca)

    # assign split units (unions near-duplicates), then bucket units to splits
    id_to_unit = assign_split_units(cands, checker=checker)
    procedural_units = {id_to_unit[c.id] for c in cands if c.procedural}
    unit_split: dict[str, str] = {}
    assignments: dict[str, dict] = {}
    for c in cands:
        u = id_to_unit[c.id]
        if u not in unit_split:
            unit_split[u] = "train" if u in procedural_units else _bucket(u, args.seed, DEFAULT_RATIOS)
        assignments[c.id] = {"split_unit_id": u, "split": unit_split[u]}

    # verify leakage-clean with the SAME checker/basis
    verify_items = [
        LeakageItem(id=c.id, split=assignments[c.id]["split"], lut_hash=c.lut_hash,
                    image_hash=c.image_hash, prompt_template_hash=c.prompt_template_hash,
                    phash=c.phash, residual_vec=c.residual_vec, prompt_text=c.prompt_text)
        for c in cands
    ]
    report = leakage_report(verify_items, checker=checker)
    split_id = _split_id(assignments)
    unit_count = len(set(id_to_unit.values()))
    dist = Counter(a["split"] for a in assignments.values())

    print(f"[freeze] split_id={split_id}  policy={args.policy_version}  units={unit_count}")
    print(f"[freeze] split dist: {dict(dist)}")
    print(f"[freeze] leakage_status={report.status}  active_axis_violations={report.per_axis_violations or 'none'}")
    print(f"[freeze] scopes checked: {report.scopes_checked}")
    print(f"[freeze] skipped axes (not-yet-wired near-neighbor): {report.skipped_axes}")
    print(f"[freeze] pca_basis_sha256={pca.basis_sha256[:16]}…  pca_fit_set_version={corpus_id}")

    if report.status != "pass":
        print(f"[freeze][ABORT] active-axis cross-split leakage: {report.per_axis_violations}")
        print(f"                examples: {report.example_pairs}")
        print("                Resolve per data_collection_plan.md; do NOT relax thresholds. Nothing written.")
        return 1

    if args.dry_run:
        print("[dry-run] leakage-clean. No files written. Re-run without --dry-run to freeze.")
        return 0

    splits_dir = root / "data" / "splits"
    splits_dir.mkdir(parents=True, exist_ok=True)
    manifest_dict = {
        "split_id": split_id,
        "leakage_policy_version": args.policy_version,
        "leakage_report_hash": report.leakage_report_hash,
        "leakage_status": report.status,
        "ratios": DEFAULT_RATIOS,
        "unit_count": unit_count,
        "frozen": True,
        "assignments": assignments,
    }
    (splits_dir / "split_manifest.json").write_text(json.dumps(manifest_dict, indent=2), encoding="utf-8")
    (splits_dir / "leakage_report.json").write_text(json.dumps(report.to_dict(), indent=2), encoding="utf-8")

    backup = splits_dir / "frozen" / split_id
    backup.mkdir(parents=True, exist_ok=True)
    shutil.copy2(splits_dir / "split_manifest.json", backup / "split_manifest.json")
    shutil.copy2(splits_dir / "leakage_report.json", backup / "leakage_report.json")
    shutil.copy2(frozen_cfg, backup / "leakage_thresholds.frozen.yaml")
    marker = {
        "split_id": split_id,
        "leakage_policy_version": args.policy_version,
        "frozen_at_utc": datetime.now(timezone.utc).isoformat(),
        "seed": args.seed,
        "ratios": DEFAULT_RATIOS,
        "split_distribution": dict(dist),
        "unit_count": unit_count,
        "accepted_candidates": cov,
        "corpus_id": corpus_id,
        "pca_basis_sha256": pca.basis_sha256,
        "active_axes": ["exact:normalized_lut_hash", "lut_behavior:pca64_cosine_near"],
        "skipped_axes": report.skipped_axes,
        "note": ("LUT-space leakage freeze (the tokenizer is LUT-only). Image/prompt semantic-near "
                 "axes need CLIP/MiniLM embeddings + teacher prompts (not yet wired); freeze those "
                 "separately for the downstream SFT."),
    }
    (backup / "frozen_split.json").write_text(json.dumps(marker, indent=2), encoding="utf-8")

    print(f"[freeze][OK] wrote {splits_dir}/split_manifest.json (frozen)")
    print(f"[freeze][OK] backup + marker -> {backup}/  (run: git add -f {backup})")
    print(f"[next] train the tokenizer on this split; record split_id={split_id} in its manifest. "
          f"Do NOT re-run the data-gen pipeline (it reshuffles the split).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
